// This file is auto-generated by buildIcons.js
import * as React from 'react';
import { iconToSVG } from '@iconify/utils';
// Import Iconify Icon as fallback
import { Icon as IconifyIcon } from "@iconify/react";

const collectionCache: Record<string, any> = {};

const loaders: Record<string, () => Promise<any>> = {
  'material-symbols': () => import('./collections/material-symbols'),
  'hugeicons': () => import('./collections/hugeicons'),
  'basil': () => import('./collections/basil'),
  'solar': () => import('./collections/solar'),
  'eos-icons': () => import('./collections/eos-icons'),
  'uil': () => import('./collections/uil'),
  'ri': () => import('./collections/ri'),
  'prime': () => import('./collections/prime'),
  'mdi': () => import('./collections/mdi'),
  'mingcute': () => import('./collections/mingcute'),
  'tabler': () => import('./collections/tabler'),
  'akar-icons': () => import('./collections/akar-icons'),
  'iconamoon': () => import('./collections/iconamoon'),
  'lets-icons': () => import('./collections/lets-icons'),
  'fluent': () => import('./collections/fluent'),
  'ion': () => import('./collections/ion'),
  'eva': () => import('./collections/eva'),
  'ph': () => import('./collections/ph'),
  'lucide': () => import('./collections/lucide'),
  'carbon': () => import('./collections/carbon'),
  'mi': () => import('./collections/mi'),
  'gg': () => import('./collections/gg'),
  'fluent-color': () => import('./collections/fluent-color'),
  'ic': () => import('./collections/ic'),
  'majesticons': () => import('./collections/majesticons'),
  'proicons': () => import('./collections/proicons'),
  'line-md': () => import('./collections/line-md'),
  'simple-icons': () => import('./collections/simple-icons'),
  'famicons': () => import('./collections/famicons'),
  'system-uicons': () => import('./collections/system-uicons'),
  'skill-icons': () => import('./collections/skill-icons'),
  'logos': () => import('./collections/logos'),
  'vscode-icons': () => import('./collections/vscode-icons'),
  'cryptocurrency': () => import('./collections/cryptocurrency'),
  'bi': () => import('./collections/bi'),
  'humbleicons': () => import('./collections/humbleicons'),
  'si': () => import('./collections/si'),
  'uim': () => import('./collections/uim'),
  'mynaui': () => import('./collections/mynaui'),
  'icon-park-solid': () => import('./collections/icon-park-solid'),
  'radix-icons': () => import('./collections/radix-icons'),
  'mage': () => import('./collections/mage'),
  'ci': () => import('./collections/ci'),
  'gravity-ui': () => import('./collections/gravity-ui'),
  'icon-park-outline': () => import('./collections/icon-park-outline'),
  'iconoir': () => import('./collections/iconoir'),
  'cil': () => import('./collections/cil'),
};

// Icon component Props interface
interface IconProps {
  icon: string;
  width?: number | string;
  height?: number | string;
  color?: string;
  className?: string;
  style?: React.CSSProperties;
  onClick?: (e: React.MouseEvent<SVGSVGElement>) => void;
}

// Icon component
export const Icon = ({ 
  icon, 
  width = 24, 
  height = 24, 
  color, 
  className = '', 
  style = {},
  onClick 
}: IconProps) => {
  const [iconData, setIconData] = React.useState<any>(null);
  const [status, setStatus] = React.useState<'loading' | 'loaded' | 'error'>(icon ? 'loading' : 'error');

  React.useEffect(() => {
    if (!icon) return;
    
    const parts = icon.split(':');
    if (parts.length < 2) {
      setStatus('error');
      return;
    }
    
    const prefix = parts[0];
    const name = parts.slice(1).join(':');
    
    if (!loaders[prefix]) {
      setStatus('error');
      return;
    }

    const loadIcon = async () => {
      try {
        if (!collectionCache[prefix]) {
          const module = await loaders[prefix]();
          collectionCache[prefix] = module.default;
        }
        
        const collection = collectionCache[prefix];
        if (collection && collection.icons && collection.icons[name]) {
          const item = collection.icons[name];
          setIconData({
            body: item.body,
            width: item.width || collection.width || 16,
            height: item.height || collection.height || 16,
          });
          setStatus('loaded');
        } else {
          setStatus('error');
        }
      } catch (err) {
        console.error(`Failed to load icon ${icon}:`, err);
        setStatus('error');
      }
    };

    loadIcon();
  }, [icon]);

  if (!icon) return null;
  
  // Use Iconify fallback if not found locally or error
  if (status === 'error') {
    return <IconifyIcon 
      icon={icon}
      width={width}
      height={height}
      color={color}
      className={className}
      style={style}
      onClick={onClick}
    />;
  }
  
  if (status === 'loading' || !iconData) {
    return <div 
      style={{ 
        width: typeof width === 'number' ? `${width}px` : width, 
        height: typeof height === 'number' ? `${height}px` : height,
        display: 'inline-block',
        ...style 
      }} 
      className={className}
    />;
  }
  
  const renderData = iconToSVG(iconData, {
    width: typeof width === 'number' ? width.toString() : width || '24',
    height: typeof height === 'number' ? height.toString() : height || '24',
  });
  
  const svgAttributes = {
    width,
    height,
    viewBox: renderData.attributes.viewBox,
    className,
    style: {
      ...style,
      color: color
    },
    dangerouslySetInnerHTML: { __html: renderData.body },
    onClick,
  };
  
  return <svg {...svgAttributes} />;
};

export default Icon;
