/**
 * Default fonts configuration for Blinko
 * These fonts are seeded into the database during initial setup
 */

export type FontSeed = {
  name: string;
  displayName: string;
  url: string | null;
  fileData: Uint8Array | null;
  isLocal: boolean;
  weights: number[];
  category: string;
  isSystem: boolean;
  sortOrder: number;
};

/**
 * System default font - uses browser's native font stack
 */
export const systemDefaultFont: FontSeed = {
  name: 'default',
  displayName: 'Default (System)',
  url: null,
  fileData: null,
  isLocal: false,
  weights: [400, 500, 600, 700],
  category: 'sans-serif',
  isSystem: true,
  sortOrder: 0,
};

/**
 * CDN-based fonts loaded via external CSS URLs
 * These fonts don't require local file storage
 */
export const cdnFonts: FontSeed[] = [
  // === Modern & Minimal Sans-Serif ===
  {
    name: 'Inter',
    displayName: 'Inter',
    url: 'https://fonts.loli.net/css2?family=Inter:wght@100..900&display=swap',
    fileData: null,
    isLocal: false,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    category: 'sans-serif',
    isSystem: false,
    sortOrder: 100,
  },
  {
    name: 'Open Sans',
    displayName: 'Open Sans',
    url: 'https://fonts.loli.net/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap',
    fileData: null,
    isLocal: false,
    weights: [300, 400, 600, 700, 800],
    category: 'sans-serif',
    isSystem: false,
    sortOrder: 101,
  },
  {
    name: 'Poppins',
    displayName: 'Poppins',
    url: 'https://fonts.loli.net/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap',
    fileData: null,
    isLocal: false,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    category: 'sans-serif',
    isSystem: false,
    sortOrder: 102,
  },
  {
    name: 'Montserrat',
    displayName: 'Montserrat',
    url: 'https://fonts.loli.net/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap',
    fileData: null,
    isLocal: false,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    category: 'sans-serif',
    isSystem: false,
    sortOrder: 103,
  },
  {
    name: 'Nunito',
    displayName: 'Nunito',
    url: 'https://fonts.loli.net/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap',
    fileData: null,
    isLocal: false,
    weights: [200, 300, 400, 500, 600, 700, 800, 900],
    category: 'sans-serif',
    isSystem: false,
    sortOrder: 104,
  },
  {
    name: 'Raleway',
    displayName: 'Raleway',
    url: 'https://fonts.loli.net/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap',
    fileData: null,
    isLocal: false,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    category: 'sans-serif',
    isSystem: false,
    sortOrder: 105,
  },
  {
    name: 'Manrope',
    displayName: 'Manrope',
    url: 'https://fonts.loli.net/css2?family=Manrope:wght@200..800&display=swap',
    fileData: null,
    isLocal: false,
    weights: [200, 300, 400, 500, 600, 700, 800],
    category: 'sans-serif',
    isSystem: false,
    sortOrder: 106,
  },
  {
    name: 'Space Grotesk',
    displayName: 'Space Grotesk',
    url: 'https://fonts.loli.net/css2?family=Space+Grotesk:wght@300..700&display=swap',
    fileData: null,
    isLocal: false,
    weights: [300, 400, 500, 600, 700],
    category: 'sans-serif',
    isSystem: false,
    sortOrder: 107,
  },
  {
    name: 'DM Sans',
    displayName: 'DM Sans',
    url: 'https://fonts.loli.net/css2?family=DM+Sans:ital,wght@0,9..40;1,9..40&display=swap',
    fileData: null,
    isLocal: false,
    weights: [400, 500, 700],
    category: 'sans-serif',
    isSystem: false,
    sortOrder: 108,
  },
  {
    name: 'Plus Jakarta Sans',
    displayName: 'Plus Jakarta Sans',
    url: 'https://fonts.loli.net/css2?family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&display=swap',
    fileData: null,
    isLocal: false,
    weights: [200, 300, 400, 500, 600, 700, 800],
    category: 'sans-serif',
    isSystem: false,
    sortOrder: 109,
  },
  {
    name: 'Outfit',
    displayName: 'Outfit',
    url: 'https://fonts.loli.net/css2?family=Outfit:wght@100..900&display=swap',
    fileData: null,
    isLocal: false,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    category: 'sans-serif',
    isSystem: false,
    sortOrder: 110,
  },
  // === Chinese Fonts ===
  {
    name: 'Noto Sans SC',
    displayName: '思源黑体 (Noto Sans SC)',
    url: 'https://fonts.loli.net/css2?family=Noto+Sans+SC:wght@100;200;300;400;500;600;700;800;900&display=swap',
    fileData: null,
    isLocal: false,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    category: 'sans-serif',
    isSystem: false,
    sortOrder: 120,
  },
  {
    name: 'Noto Serif SC',
    displayName: '思源宋体 (Noto Serif SC)',
    url: 'https://fonts.loli.net/css2?family=Noto+Serif+SC:wght@200;300;400;500;600;700;900&display=swap',
    fileData: null,
    isLocal: false,
    weights: [200, 300, 400, 500, 600, 700, 900],
    category: 'serif',
    isSystem: false,
    sortOrder: 121,
  },
  {
    name: 'Noto Sans TC',
    displayName: '思源黑体繁体 (Noto Sans TC)',
    url: 'https://fonts.loli.net/css2?family=Noto+Sans+TC:wght@100;200;300;400;500;600;700;800;900&display=swap',
    fileData: null,
    isLocal: false,
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    category: 'sans-serif',
    isSystem: false,
    sortOrder: 122,
  },
  {
    name: 'Noto Serif TC',
    displayName: '思源宋体繁体 (Noto Serif TC)',
    url: 'https://fonts.loli.net/css2?family=Noto+Serif+TC:wght@200;300;400;500;600;700;900&display=swap',
    fileData: null,
    isLocal: false,
    weights: [200, 300, 400, 500, 600, 700, 900],
    category: 'serif',
    isSystem: false,
    sortOrder: 123,
  },
  {
    name: 'Ma Shan Zheng',
    displayName: '马善政手写体',
    url: 'https://fonts.loli.net/css2?family=Ma+Shan+Zheng&display=swap',
    fileData: null,
    isLocal: false,
    weights: [400],
    category: 'handwriting',
    isSystem: false,
    sortOrder: 124,
  },
  {
    name: 'ZCOOL XiaoWei',
    displayName: '站酷小薇体',
    url: 'https://fonts.loli.net/css2?family=ZCOOL+XiaoWei&display=swap',
    fileData: null,
    isLocal: false,
    weights: [400],
    category: 'sans-serif',
    isSystem: false,
    sortOrder: 125,
  },
  {
    name: 'ZCOOL KuaiLe',
    displayName: '站酷快乐体',
    url: 'https://fonts.loli.net/css2?family=ZCOOL+KuaiLe&display=swap',
    fileData: null,
    isLocal: false,
    weights: [400],
    category: 'sans-serif',
    isSystem: false,
    sortOrder: 126,
  },
  {
    name: 'ZCOOL QingKe HuangYou',
    displayName: '站酷庆科黄油体',
    url: 'https://fonts.loli.net/css2?family=ZCOOL+QingKe+HuangYou&display=swap',
    fileData: null,
    isLocal: false,
    weights: [400],
    category: 'sans-serif',
    isSystem: false,
    sortOrder: 127,
  },
  {
    name: 'Long Cang',
    displayName: '仓耳今楷',
    url: 'https://fonts.loli.net/css2?family=Long+Cang&display=swap',
    fileData: null,
    isLocal: false,
    weights: [400],
    category: 'serif',
    isSystem: false,
    sortOrder: 128,
  },
  {
    name: 'Zhi Mang Xing',
    displayName: '站酷文艺体',
    url: 'https://fonts.loli.net/css2?family=Zhi+Mang+Xing&display=swap',
    fileData: null,
    isLocal: false,
    weights: [400],
    category: 'handwriting',
    isSystem: false,
    sortOrder: 129,
  },
  {
    name: 'JetBrains Mono',
    displayName: 'JetBrains Mono',
    url: 'https://fonts.loli.net/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap',
    fileData: null,
    isLocal: false,
    weights: [100, 200, 300, 400, 500, 600, 700, 800],
    category: 'monospace',
    isSystem: false,
    sortOrder: 200,
  },
  {
    name: 'Fira Code',
    displayName: 'Fira Code',
    url: 'https://fonts.loli.net/css2?family=Fira+Code:wght@300..700&display=swap',
    fileData: null,
    isLocal: false,
    weights: [300, 400, 500, 600, 700],
    category: 'monospace',
    isSystem: false,
    sortOrder: 201,
  },
  {
    name: 'Source Code Pro',
    displayName: 'Source Code Pro',
    url: 'https://fonts.loli.net/css2?family=Source+Code+Pro:ital,wght@0,200..900;1,200..900&display=swap',
    fileData: null,
    isLocal: false,
    weights: [200, 300, 400, 500, 600, 700, 900],
    category: 'monospace',
    isSystem: false,
    sortOrder: 202,
  },
  {
    name: 'Space Mono',
    displayName: 'Space Mono',
    url: 'https://fonts.loli.net/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap',
    fileData: null,
    isLocal: false,
    weights: [400, 700],
    category: 'monospace',
    isSystem: false,
    sortOrder: 204,
  },
  {
    name: 'Roboto Mono',
    displayName: 'Roboto Mono',
    url: 'https://fonts.loli.net/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap',
    fileData: null,
    isLocal: false,
    weights: [100, 200, 300, 400, 500, 600, 700],
    category: 'monospace',
    isSystem: false,
    sortOrder: 205,
  },
  {
    name: 'Ubuntu Mono',
    displayName: 'Ubuntu Mono',
    url: 'https://fonts.loli.net/css2?family=Ubuntu+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap',
    fileData: null,
    isLocal: false,
    weights: [400, 700],
    category: 'monospace',
    isSystem: false,
    sortOrder: 206,
  },
  {
    name: 'Inconsolata',
    displayName: 'Inconsolata',
    url: 'https://fonts.loli.net/css2?family=Inconsolata:wght@200..900&display=swap',
    fileData: null,
    isLocal: false,
    weights: [200, 300, 400, 500, 600, 700, 800, 900],
    category: 'monospace',
    isSystem: false,
    sortOrder: 207,
  },
  {
    name: 'Anonymous Pro',
    displayName: 'Anonymous Pro',
    url: 'https://fonts.loli.net/css2?family=Anonymous+Pro:ital,wght@0,400;0,700;1,400;1,700&display=swap',
    fileData: null,
    isLocal: false,
    weights: [400, 700],
    category: 'monospace',
    isSystem: false,
    sortOrder: 208,
  },
  {
    name: 'VT323',
    displayName: 'VT323 (Retro)',
    url: 'https://fonts.loli.net/css2?family=VT323&display=swap',
    fileData: null,
    isLocal: false,
    weights: [400],
    category: 'monospace',
    isSystem: false,
    sortOrder: 209,
  },
  {
    name: 'Share Tech Mono',
    displayName: 'Share Tech Mono',
    url: 'https://fonts.loli.net/css2?family=Share+Tech+Mono&display=swap',
    fileData: null,
    isLocal: false,
    weights: [400],
    category: 'monospace',
    isSystem: false,
    sortOrder: 211,
  },
];

/**
 * Get all default fonts (system + CDN)
 */
export function getDefaultFonts(): FontSeed[] {
  return [systemDefaultFont, ...cdnFonts];
}
